[build]
  publish = "."

[[redirects]]
  from = "/pos"
  to = "/pos/index.html"
  status = 200

[[redirects]]
  from = "/pos/*"
  to = "/pos/index.html"
  status = 200

[[redirects]]
  from = "/hub"
  to = "/hub.html"
  status = 200

[[redirects]]
  from = "/hub/*"
  to = "/hub.html"
  status = 200
